export const products = [
  {
    id: 1,
    title: "Cappadocia",
    price: 40000,
    stock: 12,
    description: "Cappadocia",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234370/samples/balloons.jpg",
  },
  {
    id: 2,
    title: "Sabana Africana",
    price: 123,
    stock: 12,
    description: "Sabana Africana",
    category: "Animales",
    img: "https://res.cloudinary.com/dkcs0lbjf/video/upload/v1712234361/samples/elephants.mp4",
  },
  {
    id: 3,
    title: "Gato",
    price: 123,
    stock: 12,
    description: "Gato",
    category: "Animales",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234357/samples/animals/kitten-playing.gif",
  },
  {
    id: 4,
    title: "Bosque",
    price: 123,
    stock: 12,
    description: "Bosque",
    category: "Paisaje",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234356/samples/landscapes/nature-mountains.jpg",
  },
  {
    id: 5,
    title: "Montaña",
    price: 123,
    stock: 12,
    description: "Montaña",
    category: "Paisaje",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234358/samples/landscapes/landscape-panorama.jpg",
  },
  {
    id: 6,
    title: "Pigmentos",
    price: 123,
    stock: 12,
    description: "Pigmentos",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234355/samples/food/spices.jpg",
  },
  {
    id: 7,
    title: "Perros",
    price: 123,
    stock: 12,
    description: "Perros",
    category: "Animales",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234351/samples/animals/three-dogs.jpg",
  },
  {
    id: 8,
    title: "New York",
    price: 123,
    stock: 12,
    description: "New York",
    category: "Fotografia",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234352/samples/landscapes/architecture-signs.jpg",
  },
  {
    id: 9,
    title: "Reno",
    price: 123,
    stock: 12,
    description: "Reno",
    category: "Animales",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234346/samples/animals/reindeer.jpg",
  },
  {
    id: 10,
    title: "Mar",
    price: 123,
    stock: 12,
    description: "Mar",
    category: "Paisaje",
    img: "https://res.cloudinary.com/dkcs0lbjf/image/upload/v1712234353/samples/landscapes/beach-boat.jpg",
  },
];
